work_dir: ./work_dir/uav/ctrgcn_bone_longtail
# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: /mnt/netdisk/Datasets/089-UAV-Human-v2/train_data.npy
  label_path: /mnt/netdisk/Datasets/089-UAV-Human-v2/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: True
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: /mnt/netdisk/Datasets/089-UAV-Human-v2/test_data.npy
  label_path: /mnt/netdisk/Datasets/089-UAV-Human-v2/test_label.pkl
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False
  normalization: True

# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
# min_lr: 0.0001
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 128
num_epoch: 70
nesterov: True